name = "QuantumCircuits"
uuid = "52f5b622-0dbc-4b19-b154-18c0dc35fa48"
authors = ["Jamie Mair <JamieMair@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
